// Generated from the image selection for VERKEERSBORDEN.pdf (see prisma/content/verkeersborden.ts).
// .svg: an exact match from Wikimedia Commons (all public domain), mirrored
// where the Surinamese sign is the mirror image (left-hand traffic).
// .png: no exact match exists, so the PDF's own image is used at its
// original size; `width` keeps it from being shown larger than that.
export const SIGN_IMAGES: Record<number, { file: string; width?: number; source?: string; mirrored?: true }> = {
  1: { file: "bord-01.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_B1_KB-AR_03-06-2024.svg" },
  2: { file: "bord-02.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_Wegenverkeersreglement_1950_model_11.svg" },
  3: { file: "bord-03.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_B5.svg" },
  4: { file: "bord-04.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_B15_KB-AR_03-06-2024.svg" },
  5: { file: "bord-05.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_B15f.svg" },
  6: { file: "bord-06.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_B15c.svg" },
  7: { file: "bord-07.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_C3.svg" },
  8: { file: "bord-08.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_C1.svg" },
  9: { file: "bord-09.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_C6.svg" },
  10: { file: "bord-10.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlandse_Wegenverkeersregeling_1966_figuur_19.svg" },
  11: { file: "bord-11.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_C11.svg" },
  12: { file: "bord-12.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_C27_2_KB-AR_03-06-2024.svg" },
  13: { file: "bord-13.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_C29_2,5_KB-AR_03-06-2024.svg" },
  14: { file: "bord-14.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_D1f_KB-AR_03-06-2024.svg" },
  15: { file: "bord-15.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_D1c.svg" },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  16: { file: "bord-16.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_D1.svg" },
  17: { file: "bord-17.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_C3.svg" },
  18: { file: "bord-18.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_C31a.svg" },
  19: { file: "bord-19.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_C31b.svg" },
  20: { file: "bord-20.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_C33.svg", mirrored: true },
  21: { file: "bord-21.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_F1.svg", mirrored: true },
  22: { file: "bord-22.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_F2.svg" },
  23: { file: "bord-23.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlandse_Wegenverkeersregeling_1966_figuur_44.svg", mirrored: true },
  24: { file: "bord-24.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlandse_Wegenverkeersregeling_1941_figuur_95.svg", mirrored: true },
  25: { file: "bord-25.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_A9.svg" },
  26: { file: "bord-26.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_E1.svg" },
  27: { file: "bord-27.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_D7_KB-AR_03-06-2024.svg" },
  28: { file: "bord-28.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_E4.svg" },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  29: { file: "bord-29.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_E4.svg" },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  30: { file: "bord-30.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_E4.svg" },
  31: { file: "bord-31.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_B9.svg" },
  32: { file: "bord-32.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_B11_KB-AR_03-06-2024.svg" },
  33: { file: "bord-33.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_C43_50.svg" },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  34: { file: "bord-34.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_C45_50_KB-AR_03-06-2024.svg" },
  35: { file: "bord-35.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_C43_30_KB-AR_03-06-2024.svg" },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  36: { file: "bord-36.svg", source: "https://commons.wikimedia.org/wiki/File:A1b_-_Belgium.svg" },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  37: { file: "bord-37.svg", source: "https://commons.wikimedia.org/wiki/File:A1b_-_Belgium.svg" },
  38: { file: "bord-38.svg", source: "https://commons.wikimedia.org/wiki/File:A1c_-_Belgium.svg" },
  39: { file: "bord-39.svg", source: "https://commons.wikimedia.org/wiki/File:A1d_-_Belgium.svg" },
  40: { file: "bord-40.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_B17_KB-AR_03-06-2024.svg" },
  41: { file: "bord-41.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A13_KB-AR_03-06-2024.svg" },
  42: { file: "bord-42.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A31_KB-AR_03-06-2024.svg" },
  43: { file: "bord-43.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A3_KB-AR_03-06-2024.svg" },
  44: { file: "bord-44.svg", source: "https://commons.wikimedia.org/wiki/File:A7a_-_Belgium.svg" },
  45: { file: "bord-45.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A7c_KB-AR_03-06-2024.svg" },
  46: { file: "bord-46.svg", source: "https://commons.wikimedia.org/wiki/File:A7b_-_Belgium.svg" },
  47: { file: "bord-47.svg", source: "https://commons.wikimedia.org/wiki/File:A15_-_Belgium.svg" },
  48: { file: "bord-48.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_F45.svg" },
  49: { file: "bord-49.png", width: 152 },
  50: { file: "bord-50.png", width: 152 },
  51: { file: "bord-51.svg", source: "https://commons.wikimedia.org/wiki/File:A21_-_Belgium.svg" },
  52: { file: "bord-52.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_A23.svg" },
  53: { file: "bord-53.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A43_KB-AR_03-06-2024.svg" },
  54: { file: "bord-54.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A11.svg" },
  55: { file: "bord-55.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A25.svg" },
  56: { file: "bord-56.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A39_KB-AR_03-06-2024.svg", mirrored: true },
  57: { file: "bord-57.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_J30.svg" },
  58: { file: "bord-58.svg", source: "https://commons.wikimedia.org/wiki/File:A33_-_Belgium.svg" },
  // Drawn here in the style of Model 43 (Nederlands verkeersbord E4): Commons has no H sign.
  59: { file: "bord-59.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_E4.svg" },
  60: { file: "bord-60.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlandse_Wegenverkeersregeling_1966_figuur_57b.svg" },
  61: { file: "bord-61.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_G4_zb.svg" },
  62: { file: "bord-62.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_A14.svg" },
  63: { file: "bord-63.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_D1_zb.svg", mirrored: true },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  64: { file: "bord-64.svg", source: "https://commons.wikimedia.org/wiki/File:A1b_-_Belgium.svg" },
  65: { file: "bord-65.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlandse_Wegenverkeersregeling_1966_figuur_61.svg" },
  66: { file: "bord-66.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_D5.svg" },
  67: { file: "bord-67.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlandse_Wegenverkeersregeling_1966_figuur_27.svg" },
  // Drawn here after the PDF, in the style of the Commons sign below: Commons has no match.
  68: { file: "bord-68.svg", source: "https://commons.wikimedia.org/wiki/File:A1b_-_Belgium.svg" },
  69: { file: "bord-69.svg", source: "https://commons.wikimedia.org/wiki/File:A1b_-_Belgium.svg" },
  70: { file: "bord-70.png", width: 250 },
  71: { file: "bord-71.png", width: 100 },
  72: { file: "bord-72.svg", source: "https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_L2.svg" },
  73: { file: "bord-73.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_traffic_sign_E3_KB-AR_03-06-2024.svg" },
  74: { file: "bord-74.svg", source: "https://commons.wikimedia.org/wiki/File:Belgian_road_sign_D03.svg" },
  75: { file: "bord-75.png", width: 255 },
};
